---
- name: Drop systemd unit file
  template:
    src: elastalert-systemd.service.j2
    dest: /lib/systemd/system/elastalert.service
    owner: root
    group: root
  notify: reload systemd
  tags: systemd

- name: Drop core elastalert config
  template:
    dest: "{{ elastalert_etc_root }}/config.yaml"
    src: config.yaml.j2
    owner: root
    group: "{{ elastalert_group }}"
    mode: "0640"
  tags: systemd
  notify: restart elastalert

- name: Check for existing elastalert index
  uri:
    url: "{{ elastalert_es_url }}/{{ elastalert_es_writeback_index }}"
    method: HEAD
    status_code: 200
  register: elastalert_index_result
  changed_when: false
  ignore_errors: yes

- name: Create index
  shell: >
    source ./venv/bin/activate &&
    ./venv/bin/elastalert-create-index
    --config {{ elastalert_etc_root }}/config.yaml
    --index {{ elastalert_es_writeback_index }}
    --old-index ''
  args:
    chdir: "{{ elastalert_venv_rootdir }}"
    executable: /bin/bash
  when: elastalert_index_result is failed
  become_user: "{{ elastalert_user }}"
  become: yes

- name: Read File system stats of the rules directory
  stat:
    path: "{{ elastalert_etc_root }}/{{ elastalert_rules_dir }}"
  register: rules_dir_stats

- name: Fail installation when rules directory exists as a file
  fail:
    msg: "The rules directory already exists but it is a file"
  when: rules_dir_stats.stat.exists and rules_dir_stats.stat.isreg

- name: Create rules folder
  file:
    path: "{{ elastalert_etc_root }}/{{ elastalert_rules_dir }}/"
    owner: root
    group: "{{ elastalert_group }}"
    mode: "0750"
    state: directory

- name: Copy over alert files
  copy:
    src: "{{ item }}"
    dest: "{{ elastalert_etc_root }}/{{ elastalert_rules_dir }}/"
    owner: root
    group: "{{ elastalert_group }}"
    mode: "0640"
    validate: "{{ elastalert_venv_rootdir }}/venv/bin/elastalert-test-rule --config {{ elastalert_etc_root }}/config.yaml %s"
  with_fileglob: "{{ elastalert_rules_files }}"
  notify: restart elastalert

- name: Deploy rules from templates
  template:
    src: "{{ item }}"
    dest: "{{ elastalert_etc_root }}/{{ elastalert_rules_dir }}/{{ item | basename | regex_replace('\\.j2' ,'') }}"
    owner: root
    group: "{{ elastalert_group }}"
    mode: "0640"
    validate: "{{ elastalert_venv_rootdir }}/venv/bin/elastalert-test-rule --config {{ elastalert_etc_root }}/config.yaml %s"
  with_fileglob: "{{ elastalert_rules_templates }}"
  notify: restart elastalert

- name: Deploy rules from variables
  copy:
    content: "{{ item | to_nice_yaml(explicit_start=true) }}"
    dest: "{{ elastalert_etc_root }}/{{ elastalert_rules_dir }}/{{ item.name | replace(' ', '-') | lower }}.yml"
    owner: root
    group: "{{ elastalert_group }}"
    mode: "0640"
    validate: "{{ elastalert_venv_rootdir }}/venv/bin/elastalert-test-rule --config {{ elastalert_etc_root }}/config.yaml %s"
  with_items: "{{ elastalert_rules }}"
  notify: restart elastalert

- name: Enable elastalert service
  service:
    name: elastalert
    enabled: yes
