---
version: 2
jobs:
  build:
    working_directory: /root/ansible-role-elastalert
    docker:
      - image: quay.io/freedomofpress/circleci-docker:latest
    steps:
      - checkout

      - setup-docker-engine

      - run:
          name: Ansible playbook test
          command: make

workflows:
  version: 2
  fpf_elastalert_role_ci:
    jobs:
      - build
